### ISSUE TITLE
Not able to run kerigo locally

### ISSUE THREAD

**Issue by shoyebinamdar** [decentralized-identity/kerigo#38]
Hi Team,

I have been trying to run the kerigo on my local system since last 3 days but with no luck.
Steps which I followed,

1. Downloaded the kerigo from github
2. built one demo file using `go build -o ./bin/bob.exe cmd/demo/bob/bob.go`
3. Run the executable `bob.exe -e 10`

But  when I run the above exe I am getting following error,

```
Direct Mode demo of Bob as EH7Oq9oxCgYa-nnNLvwhp9sFZpALILlRYyB-6n4WDi7w on TCP port 5620 to port 8080


remove C:\Users\shoye\AppData\Local\Temp\keri-bob-906566335\000000.vlog: The process cannot access the file because it is being used by another process.
panic: unable to connect after timeout: unable to connect: dial tcp :8080: connectex: No connection could be made because the target machine actively refused it.

goroutine 1 [running]:
main.main()
        C:/Users/shoye/workspace/go/src/kerigo-master/cmd/demo/bob/bob.go:73 +0x605
```

I could see three issue here,

1. badger db is obtaining lock on the temp directory due to which program cannot delete the log file when it terminates
2. keri-bob-906566335\000000.vlog is very huge almost 2GB, what could be the reason? is it because it contains the badger db? if yes how can I reduce it a bit
3. Why am I getting connection refused error? am I missing something?

I didn't had enough documentation to follow so I might have missed some minor steps, any help would be appreciated.

**Comment by pfeairheller** [comment]
Thanks for the report.  I'll take a look later this morning

**Comment by shoyebinamdar** [comment]
@pfeairheller Did you got chance to look at it? I am actually stuck here

**Comment by shoyebinamdar** [comment]
@pfeairheller any update on this?

**Comment by pfeairheller** [comment]
Sorry for the delay, I've moved on to working full time on `keripy` and during the transition the last two weeks I've had no time to look at this.

There are several things going on here.  First of all, the database issues.  The sample apps had a `defer` to delete the directory containing the temp database but they did not have a `defer` to close the database first.  On my Linux box, I have not seen the error about deleting the directory, but I have noticed that the directories are getting stranded when the app don't end gracefully.  In both Eve and Bob I added the database close `defer` and now I see the database directory disappear.   I just merged a PR that adds the database closing `defer`.

As for the size issue you are seeing, I can not replicate that on my Linux box (data files are 2152 bytes when stranded) and I fear it is a badgerdb / Windows issue.   I do not have a Windows machine so perhaps you can look into Badger and see if there are any reported issues for Windows.

Finally, the Bob demo is attempting to connect to either Sam or Eve.  So in order to see Bob do _something_ you need to run Bob alongside either Eve or Sam.  Then Bob will connect in direct mode and exchange KELs with the other participant.  So you are specifying a 10 second timeout with your command line and thus the `panic` is correct because Bob is timing out waiting for someone to connect to.

**Comment by shoyebinamdar** [comment]
Thanks @pfeairheller for the update.
